### PR TITLE
content: 1.2.19

### PR DESCRIPTION
**Pull request by esmeetewinkel**
Update config following merge of https://github.com/IDEMSInternational/parenting-app-ui/pull/2269 to remove now redundant line.

### CODE REVIEW

**Comment by esmeetewinkel** [comment]
@jfmcquade could it be that the deployment preview action is failing because of this removed config line?

**Comment by jfmcquade** [comment]
I did try running the action with this repo pointing to the `v0.16.28` code version just in case, which [failed in the same way](https://github.com/IDEMSInternational/app-debug-content/actions/runs/8569087179/job/23490505004?pr=61).

There doesn't seem to be anything relevant in the [actions cache](https://github.com/IDEMSInternational/app-debug-content/actions/caches).

So I reverted the deletion of the line that sets `config.app_data.output_path = "./app_data"` in the config, and it has now built successfully. So for some reason the default value for `output_path`, as it now exists on master, isn't being used correctly, but I'm not sure why yet.

**Comment by jfmcquade** [comment]
I wondered if it my be related to this repo not having a `DEPLOYMENT_PRIVATE_KEY` secret to decrypt the encrypted config files, somehow causing the deployment config to not be compiled correctly, but I've added one and the action is [still failing in the same way](https://github.com/IDEMSInternational/app-debug-content/actions/runs/8599887346/job/23564333302).

Although I did notice a related potential issue: as part of the deployment set workflow, `decrypt`, runs after the deployment is compiled. This means that when setting a deployment for the first time, the decrypted files are not found and, presumably, the values are not included in the compiled config.
Screenshot 2024-04-08 at 14 12 52

 @chrismclarke do you think this is a genuine issue following the [firebase config PR](https://github.com/IDEMSInternational/parenting-app-ui/pull/2235), or am I misunderstanding? A fix might be to add a step to `reusable-app-build` to decrypt the config encrypted folder directly after running `Populate Encryption key`.

Also @chrismclarke, any thoughts on why the build action on this PR could be failing? I don't get any issues with the `output_path` value being correctly included in the compiled config when I work on this branch locally. As outlined in the conversation above, adding back in the `config.app_data.output_path = "./app_data"` line does allow the action to run successfully.

**Comment by jfmcquade** [comment]
OK, I found the issue: in https://github.com/IDEMSInternational/parenting-app-ui/pull/2269 I set the default to `"./app-data"`, where it should be `"./app_data"` 🤦

In trying to fix it, I accidentally pushed directly to master, see [this commit](https://github.com/IDEMSInternational/parenting-app-ui/commit/eb209a8e05860be6e6592ade5ee342bcc8713f07). I didn't think pushing to master was possible, shouldn't our branch protection rules prevent that, @ChrisMarsh82 ?

**Review by jfmcquade — APPROVED** [review]

**Comment by ChrisMarsh82** [comment]
@jfmcquade we do have this set up on parenting-app-ui
image
However, you can bypass this as an administrator.

**Comment by jfmcquade** [comment]
> However, you can bypass this as an administrator.
> 
> We can set this up so it can't be bypassed by admin but it would mean you will always need a review. This could cause issues with quick fixes.

Thanks, that makes sense. I wasn't aware that admins could bypass the branch protection rules. On balance I'd probably rather I didn't have the power to do so directly from the CLI with `git push`, but it's true that it may sometimes be required for quick fixes. Good to be aware of, I'll be more careful from now on

**Comment by chrismclarke** [comment]
@ChrisMarsh82 @jfmcquade 
I'd say the safest option is probably to disable administrator bypass. If urgent fixes are required admins can still untoggle the option in repo settings so more like a 2-step bypass which is probably worth it given the potential to accidentally push commits directly to master (I've definitely made that mistake in the past myself)

**Comment by esmeetewinkel** [comment]
>I'd say the safest option is probably to disable administrator bypass.

It seems someone disabled administrator bypass

image

**Pull request merged**
